### PR TITLE
[FB] BMS | Add button to hide sidebar

### PR DESCRIPTION
**Pull request by Sasikuttan2163**
Add button to hide browser manager sidebar.
image

### CODE REVIEW

**Comment by TheChilledBuffalo** [comment]
Looks good! Useful feature for users!

**Comment by surapunoyousei** [comment]
So... We should use another icon. Thinking it.

**Comment by TheChilledBuffalo** [comment]
Maybe you can use this as a reference?

image

It is the icon for the same purpose in Edge.

**Comment by surapunoyousei** [comment]
I will search about icon.

**Comment by surapunoyousei** [comment]
OK. Merge this PR. I will replace icon with new one

**Comment by CutterKnife** [comment]
I have created a dedicated icon. Thank you for your PR!

**Pull request merged**
