### PR TITLE
[FB] SSB | Desktop Entry Support for Linux

### PR DESCRIPTION
**Pull request by Sasikuttan2163**
Add support for adding and deleting `.desktop` files for SSB apps on Linux. 

Flatpak support is still being worked on.

Agents, you can connect with the contact here kwwsv://mrlq.oxjylwf.qhw/XJYxC3YselEWhZ5ndZQkgJXjT29xgJImgD

### CODE REVIEW

**Comment by TheChilledBuffalo** [comment]
@surapunoyousei This PR is ready for review. :)

**Comment by GunGunGun** [comment]
Thank you very much for your hardwork! We're getting there.

**Comment by TheChilledBuffalo** [comment]
We cooked!

**Comment by Mikilio** [comment]
I seem to still have the issue on NixOS though. I have no idea how to debug this without building myself.

**Pull request merged**
