### PR TITLE
[FB] Vertical Tabs | Fixed website resizing and margin in webpanels

### PR DESCRIPTION
**Pull request by Axenide**
Fixed website resizing when hovering over collapsed tabs and margin inside webpanels when collapsed tabs are active.
https://github.com/Floorp-Projects/Floorp/issues/1050 (I couldn't find the original issue)
https://github.com/Floorp-Projects/Floorp/issues/1096

### CODE REVIEW

**Comment by TheChilledBuffalo** [comment]
@Axenide I'm sorry but this can't be accepted. Like you yourself mentioned in the issue thread, `53px` is specific to your environment and so it can't be accepted as a global solution.

**Comment by TheChilledBuffalo** [comment]
@Axenide But what does the width of the Vertical Tabs to do here? And check the video below, your PR brings back the issue that I was trying to fix at first, i.e., the website gets resized on hovering over the tab bar and the webpanels are no longer resizable.

https://github.com/Floorp-Projects/Floorp-core/assets/87632612/4610bc5c-31c1-456e-8d66-dd5271fc2ae5

**Comment by TheChilledBuffalo** [comment]
I'll tell you what's happening. The Floorp Sidebar works like a browser inside a browser. I fixed the website resizing problem by adding a margin to `#appcontent`. However, as I said before, the sidebar also runs basically a new browser window, and so has another `#appcontent` inside it. So the margin gets applied there as well. That's what's causing this issue.

We need to figure out a way to exclude the `#appcontent`s in the Sidebar and only apply the margin to the main `#appcontent`.

**Comment by Axenide** [comment]
Oh, you are right about not being able to resize the panels. :(
However, as you can see, with your commit the resizing issue wasn't fixed, at least on my end. This is a recording of a *fresh* profile:

https://github.com/Floorp-Projects/Floorp-core/assets/66109459/4d1a7a86-4c9b-4cd9-b6a5-70da1b90fb7b

This is after applying my changes, sidepanels can only be resized with their toolbar.

https://github.com/Floorp-Projects/Floorp-core/assets/66109459/edc3898f-7c61-41d5-9da6-df517c9222a2

I'll keep researching to see if there is a way to exclude the `#appcontent`.

**Comment by Axenide** [comment]
Setting `#sidebar-splitter2` position to relative fixed the sidepanel resizing.

https://github.com/Floorp-Projects/Floorp-core/assets/66109459/8a13350c-8160-414f-b62f-cd8b281ab5a6

**Comment by TheChilledBuffalo** [comment]
@Axenide yeah the splitter issue seems to be fixed, But I'm really not convinced about the `53px` value because `27px` seems to the be the right value for others I talked to as well.... You really sure you don't have any custom modifications? Because the expanded vertical tabbar in your videos seem to be transparent...

**Comment by TheChilledBuffalo** [comment]
Or a better solution would be to write a JS function that dynamically sets the value depending on the specific environment. Maybe hardcoding the values are not the best option....

**Comment by Axenide** [comment]
> @Axenide yeah the splitter issue seems to be fixed, But I'm really not convinced about the `53px` value because `27px` seems to the be the right value for others I talked to as well.... You really sure you don't have any custom modifications? Because the expanded vertical tabbar in your videos seem to be transparent...

The tabbar is transparent because of my GTK theme, but that's a new profile. The only thing I made was enabling collapsible vertical tabs.

I tried this on my other computer and the result is exactly the same.

Also, you are right, hardcoding isn't the best option. This is an "it works on my machine" moment. :/

**Comment by DonJaviJavi** [comment]
Hi all,
I have the same issue using the flatpak version on Fedora Linux 39.
But in my case, I also have the tabs changing height on hover.
I can´t find `native-verticaltab-hover.css` file anywhere in the flatpak installation, neither other css files, only `userChrome.css` and `userContent.css` which are almost empty.
[Screencast from 2024-05-11 20-49-45.webm](https://github.com/Floorp-Projects/Floorp-core/assets/68520379/6b093745-9257-402d-bd5a-1c39d6ed7dcc)
I tried with a new profile, but the problem remains.

Thank you!

**Comment by Axenide** [comment]
> Hi all, I have the same issue using the flatpak version on Fedora Linux 39. But in my case, I also have the tabs changing height on hover. I can´t find `native-verticaltab-hover.css` file anywhere in the flatpak installation, neither other css files, only `userChrome.css` and `userContent.css` which are almost empty.
> Screencast.from.2024-05-11.20-49-45.mp4
> 
> I tried with a new profile, but the problem remains.
> 
> Thank you!

Same here.

**Comment by TheChilledBuffalo** [comment]
@Axenide Can you check if the website resizing occurs in the latest version of Floorp? According to @Sasikuttan2163 this issue doesn't occur anymore.

**Comment by Axenide** [comment]
> @Axenide Could you check if the website resizing occurs in the latest version of Floorp? According to @Sasikuttan2163 this issue doesn't occur anymore.

Just updated, still present.

**Comment by TheChilledBuffalo** [comment]
@Axenide do you have a better idea to fix this issue? If not, this PR can be closed I think.

**Comment by Axenide** [comment]
@TheChilledBuffalo Not right now, I haven't been thinking of this since I switched to Sidebery, and now this conflicts so I'll close. Thanks for the reminder. :)

**Pull request closed without merging**
