### PR TITLE
Add Types about XPCOM!

### PR DESCRIPTION
**Pull request by nyanrus**
# XPIDL2DTS
Finally the XPCOM types are added with this PR!
https://github.com/nyanrus/XPIDL2DTS
it is still experimental and unstable but useful enough

## features
- `Components` types (including Cc, Cu, Ci, etc)
- `ChromeUtils` type
- `Services` type
- etc.

## Steps to Use Types
1. in floorp Folder, run
```
//if you didn't install pnpm,
//npm i -g pnpm

//install dependencies
pnpm install

//generate types
pnpm gen
```
and enjoy the types!

I recommend this extension to use typescript
https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

### CODE REVIEW

**Comment by surapunoyousei** [comment]
レビュー開始

**Comment by surapunoyousei** [comment]
pnpm gen でエラー

image

**Comment by nyanrus** [comment]
それ想定済み

**Comment by surapunoyousei** [comment]
マージするかぁよくわからんけど

**Pull request merged**
